Добавлено правило поиска отозванных NPM зависимостей
POSIdev-community/ptai-analysis-rules pull request #9
Opened 2024-04-16 19:54 UTC by sergiomarotco

2024-04-17 07:28 UTC, vldF commented on custom-rules/Vulnerable and Outdated Components/NPM-deprecated_packages.json
> +    "Key": "Android (Kotlin/JAVA). Зависимость зашита в исходном коде",
А причем тут Kotlin/Java и NPM?

2024-04-17 07:34 UTC, vldF commented
[x] Добавить JSON-файл с правилом в соответствующую директорию внутри [custom-rules](https://github.com/POSIdev-community/ptai-analysis-rules/blob/main/custom-rules). Правило нужно добавить или в уже существующую поддиректорию или, если подходящей нет, создать новую

[ ] При добавлении новой поддиректории: необходимо создать файл README.md с описанием новых правил
[X] Необходимо обновить [README.md](https://github.com/POSIdev-community/ptai-analysis-rules/blob/main/custom-rules/README.md). Описание правила можно продублировать из предыдущего пункта

2024-04-17 07:34 UTC, vldF requested changes

2024-04-17 07:34 UTC, vldF commented on custom-rules/README.md
> +    Разработчик отозвал зависимость. Это может быть по разным причинам, например, разработчик более не развивает проект из-за отсутствия    заинтересованности либо в новых версиях фреймворка/языка фу
```suggestion
    Разработчик отозвал зависимость. Это может быть по разным причинам, например, разработчик более не развивает проект из-за отсутствия заинтересованности либо в новых версиях фреймворка/языка функционал используемой зависимости полностью или частично уже реализован, либо зависимость содержит уязвимость, которая устранена в следующих версиях.
```

2024-04-17 07:41 UTC, vldF commented
- [X] Добавить JSON-файл с правилом в соответствующую директорию внутри [custom-rules](https://github.com/POSIdev-community/ptai-analysis-rules/blob/main/custom-rules). Правило нужно добавить или в уже существующую поддиректорию или, если подходящей нет, создать новую

- [ ] При добавлении новой поддиректории: необходимо создать файл README.md с описанием новых правил

- ~~[ ] При добавлении правил в уже существующую: необходимо обновить README.md в ней~~
- [X] Необходимо обновить [README.md](https://github.com/POSIdev-community/ptai-analysis-rules/blob/main/custom-rules/README.md). Описание правила можно продублировать из предыдущего пункта
- ~~[ ] Для Regex правил добавьте ссылку на [regex101.com](https://regex101.com/) или аналогичный сайт. Постарайтесь учесть все возможные случаи срабатывания и несрабатывания всех новых правил~~

Добавьте, пожалуйста, описание в новую директорию. Да, сейчас это выглядит как бесполезное копирование текста из места в место, но в будущем это позволит упростить навигацию. И у нас есть планы на автоматизацию этого, просто мы не можем сделать это прямо сейчас

2024-05-16 19:39 UTC, sergiomarotco commented
> Добавьте, пожалуйста, описание в новую директорию. Да, сейчас это выглядит как бесполезное копирование текста из места в место, но в будущем это позволит упростить навигацию. И у нас есть планы на автоматизацию этого, просто мы не можем сделать это прямо сейчас

@vldF исполнено

2024-05-17 12:02 UTC, vldF approved these changes

2024-05-17 12:02 UTC, vldF commented
Спасибо!

2024-05-18 09:23 UTC, merged